title:              Taewoon Kim
email:              tae898@gmail.com
description:        Artificial Intelligence Researcher & Engineer
author:             Taewoon Kim
baseurl:            ""
url:                "https://taewoon.kim"

# Social Profiles
x_username:   tae898
github_username:    tae898
# facebook_username:  StartBootstrap
# instagram_username: tae898  
linkedin_username:  tae898
google_scholar:     https://scholar.google.com/citations?user=dJ4ksGoAAAAJ&hl=en
youtube:            tae898

# Add your google-analytics ID here to activate google analytics
# google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
